In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("C:/Users/Prabhjyot/Desktop/Data Science_ML/Practice/ML_Diamonds/diamonds.csv")
print(df.shape)
print(df.info())

(53940, 11)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 11 columns):
Unnamed: 0    53940 non-null int64
carat         53940 non-null float64
cut           53940 non-null object
color         53940 non-null object
clarity       53940 non-null object
depth         53940 non-null float64
table         53940 non-null float64
price         53940 non-null int64
x             53940 non-null float64
y             53940 non-null float64
z             53940 non-null float64
dtypes: float64(6), int64(2), object(3)
memory usage: 4.5+ MB
None


In [4]:
# we see that there are 11 columns and 53940 rows. And there are no null fields
print(df.head())

   Unnamed: 0  carat      cut color clarity  depth  table  price     x     y  \
0           1   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98   
1           2   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84   
2           3   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07   
3           4   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23   
4           5   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35   

      z  
0  2.43  
1  2.31  
2  2.31  
3  2.63  
4  2.75  


In [5]:
# Unnamed column can be removed as it has no effect on price
df = df.drop([df.columns[0]], axis = 1)

In [6]:
print(df.head())

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75


In [7]:
# check the statistics
print(df.describe())


              carat         depth         table         price             x  \
count  53940.000000  53940.000000  53940.000000  53940.000000  53940.000000   
mean       0.797940     61.749405     57.457184   3932.799722      5.731157   
std        0.474011      1.432621      2.234491   3989.439738      1.121761   
min        0.200000     43.000000     43.000000    326.000000      0.000000   
25%        0.400000     61.000000     56.000000    950.000000      4.710000   
50%        0.700000     61.800000     57.000000   2401.000000      5.700000   
75%        1.040000     62.500000     59.000000   5324.250000      6.540000   
max        5.010000     79.000000     95.000000  18823.000000     10.740000   

                  y             z  
count  53940.000000  53940.000000  
mean       5.734526      3.538734  
std        1.142135      0.705699  
min        0.000000      0.000000  
25%        4.720000      2.910000  
50%        5.710000      3.530000  
75%        6.540000      4.040000  


In [8]:
# convert categorical to binary vectors
df1 = pd.get_dummies(df,prefix_sep='_', drop_first=True)
df1.head()

carat  depth  table  price     x     y     z  cut_Good  cut_Ideal  \
0   0.23   61.5   55.0    326  3.95  3.98  2.43         0          1   
1   0.21   59.8   61.0    326  3.89  3.84  2.31         0          0   
2   0.23   56.9   65.0    327  4.05  4.07  2.31         1          0   
3   0.29   62.4   58.0    334  4.20  4.23  2.63         0          0   
4   0.31   63.3   58.0    335  4.34  4.35  2.75         1          0   

   cut_Premium      ...       color_H  color_I  color_J  clarity_IF  \
0            0      ...             0        0        0           0   
1            1      ...             0        0        0           0   
2            0      ...             0        0        0           0   
3            1      ...             0        1        0           0   
4            0      ...             0        0        1           0   

   clarity_SI1  clarity_SI2  clarity_VS1  clarity_VS2  clarity_VVS1  \
0            0            1            0            0             0   
1            1            0            0            0             0   
2            0            0            1            0             0   
3            0            0            0            1             0   
4            0            1            0            0             0   

   clarity_VVS2  
0             0  
1             0  
2             0  
3             0  
4             0  

[5 rows x 24 columns]

In [9]:
# Pairwise correlation matrix
corr = df1.corr()
corr.style.background_gradient(cmap='coolwarm').set_precision(2)


In [10]:
# VIF calculation
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.tools.tools import add_constant

VIF = add_constant(df1)
pd.Series([variance_inflation_factor(VIF.values, i) 
               for i in range(VIF.shape[1])], 
              index=VIF.columns)


const            7041.268085
carat              44.743271
depth               1.788946
table               1.790506
price              12.467506
x                  58.520407
y                  20.592254
z                  23.586562
cut_Good            3.962344
cut_Ideal          11.439056
cut_Premium         8.434645
cut_Very Good       7.702974
color_E             2.015046
color_F             2.021610
color_G             2.224280
color_H             2.049797
color_I             1.862482
color_J             1.640197
clarity_IF          4.245964
clarity_SI1        16.691529
clarity_SI2        12.275574
clarity_VS1        12.883324
clarity_VS2        16.768777
clarity_VVS1        7.174677
clarity_VVS2        9.191331
dtype: float64

In [11]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split

X = df1.drop('price', axis=1)
print(X.head())

Price = df1['price']
#Features_train, Features_test, Price_train, Price_test = train_test_split(Features, Price, test_size=0.30, random_state=42)
X_train, X_test, Price_train, Price_test = train_test_split(X, Price, test_size=0.3, random_state=42)

   carat  depth  table     x     y     z  cut_Good  cut_Ideal  cut_Premium  \
0   0.23   61.5   55.0  3.95  3.98  2.43         0          1            0   
1   0.21   59.8   61.0  3.89  3.84  2.31         0          0            1   
2   0.23   56.9   65.0  4.05  4.07  2.31         1          0            0   
3   0.29   62.4   58.0  4.20  4.23  2.63         0          0            1   
4   0.31   63.3   58.0  4.34  4.35  2.75         1          0            0   

   cut_Very Good      ...       color_H  color_I  color_J  clarity_IF  \
0              0      ...             0        0        0           0   
1              0      ...             0        0        0           0   
2              0      ...             0        0        0           0   
3              0      ...             0        1        0           0   
4              0      ...             0        0        1           0   

   clarity_SI1  clarity_SI2  clarity_VS1  clarity_VS2  clarity_VVS1  \
0            0       

In [12]:
print("X", X.shape)
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)

X (53940, 23)
X_train: (37758, 23)
X_test: (16182, 23)


In [13]:
from sklearn.linear_model import LinearRegression

print("\nLINEAR (subset)")
rgr = LinearRegression(normalize=True)
rgr.fit(X_train, Price_train)
print("model:", rgr)
print("coeffs:", rgr.coef_)
print("intercept:", rgr.intercept_)

#Evaluate the predictions of the model
Price_predictions_regression = rgr.predict(X_test)
print('R squared:', rgr.score(X_test, Price_test))
print(Price_predictions_regression[:10])
print(Price_test[:10])

Price_predictions_regression


LINEAR (subset)
model: LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=True)
coeffs: [ 1.12262051e+04 -6.31199113e+01 -2.70960563e+01 -9.80549238e+02
 -5.63315299e+00 -4.81547644e+01  5.95521080e+02  8.46196258e+02
  7.77769963e+02  7.43301360e+02 -2.17028968e+02 -2.73303976e+02
 -5.00160238e+02 -9.98634669e+02 -1.47608423e+03 -2.38198979e+03
  5.45903730e+03  3.75170967e+03  2.78194055e+03  4.65783431e+03
  4.33672558e+03  5.10133518e+03  5.02829553e+03]
intercept: 2041.2862777695127
R squared: 0.9201866914388087
[ 711.56570501 3197.40419579 1943.02948182 2080.07561855 9871.56234383
 3941.19403297 2380.50740952 2377.76870584 2849.51603502 6193.3930034 ]
1388      559
50052    2201
41645    1238
42377    1304
17244    6901
1608     3011
46398    1765
45493    1679
49385    2102
10460    4789
Name: price, dtype: int64


array([  711.56570501,  3197.40419579,  1943.02948182, ...,
       10609.79287119,  4105.70876126,  1993.88821027])

In [14]:
print("\n\nRIDGE")
from sklearn.linear_model import Ridge
ridge = Ridge(alpha = 0.001, normalize=True)
ridge.fit(X_train, Price_train)
print("model:", ridge)
print("ridge coeffs:", ridge.coef_)
print("ridge intercept:", ridge.intercept_)
Price_predictions = ridge.predict(X_test)
print('Ridge R squared:', ridge.score(X_test, Price_test))
print(Price_predictions_regression[:10])
print(Price_test[:10])




RIDGE
model: Ridge(alpha=0.001, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=True, random_state=None, solver='auto', tol=0.001)
ridge coeffs: [10925.01587025   -58.67205704   -27.50310767  -842.73547965
   -13.04881922   -63.35273217   601.93412349   853.16704164
   784.74428209   753.85685954  -212.91240653  -271.48357188
  -494.84615558  -988.31164435 -1459.3484484  -2360.07084704
  5206.10929563  3492.69770647  2530.77500572  4398.63761075
  4079.34339431  4848.86703898  4773.28304285]
ridge intercept: 1575.570321124951
Ridge R squared: 0.9201516109045541
[ 711.56570501 3197.40419579 1943.02948182 2080.07561855 9871.56234383
 3941.19403297 2380.50740952 2377.76870584 2849.51603502 6193.3930034 ]
1388      559
50052    2201
41645    1238
42377    1304
17244    6901
1608     3011
46398    1765
45493    1679
49385    2102
10460    4789
Name: price, dtype: int64


In [15]:
print("\n\nLASSO")
from sklearn.linear_model import Lasso
lasso = Lasso(alpha = 0.001, normalize=True)
lasso.fit(X_train, Price_train)
print(lasso)
print("Lasso coeffs:", lasso.coef_)
print("Lasso intercept:", lasso.intercept_)
Price_predictions = lasso.predict(X_test)
print('Lasso R squared:', lasso.score(X_test, Price_test))
print(Price_predictions[:10])
print(Price_test[:10])



LASSO
Lasso(alpha=0.001, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=True, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)
Lasso coeffs: [ 1.12054137e+04 -6.31945402e+01 -2.71945999e+01 -9.73354356e+02
 -4.84891691e+00 -4.81018146e+01  5.87134344e+02  8.38033348e+02
  7.69487930e+02  7.35386573e+02 -2.13424410e+02 -2.69895193e+02
 -4.96365771e+02 -9.94551736e+02 -1.47129449e+03 -2.37672464e+03
  5.42432547e+03  3.71786070e+03  2.74850473e+03  4.62355332e+03
  4.30290235e+03  5.06714407e+03  4.99419210e+03]
Lasso intercept: 2060.1629952834373
Lasso R squared: 0.9202031777918325
[ 708.57144154 3199.08106334 1942.99461149 2080.46821786 9869.70272604
 3952.26789092 2381.56776057 2375.14000271 2851.39420235 6194.96431693]
1388      559
50052    2201
41645    1238
42377    1304
17244    6901
1608     3011
46398    1765
45493    1679
49385    2102
10460    4789
Name: price, dtype: int64


In [16]:
from sklearn import tree
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score

clf_tree = tree.DecisionTreeClassifier(criterion="entropy", max_depth=5)
clf_tree.fit(X_train, Price_train)
print(clf_tree)
tree_predictions = clf_tree.predict(X_test)
print(confusion_matrix(Price_test, tree_predictions))
print("f1:", f1_score(Price_test, tree_predictions, average=None))
print("f1:", f1_score(Price_test, tree_predictions, average='micro'))

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=5,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
f1: [0. 0. 0. ... 0. 0. 0.]
f1: 0.014769496971944136


C:\Users\Prabhjyot\Anaconda3\Anaconda4\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Prabhjyot\Anaconda3\Anaconda4\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [24]:
#from sklearn.ensemble import RandomForestClassifier
#clf_rf = RandomForestClassifier(n_estimators = 10, criterion='entropy')
#clf_rf.fit(X_train, Price_train)
#print(clf_rf)
#rf_predictions = clf_rf.predict(X_test)
#print(confusion_matrix(Price_test, rf_predictions))
#print("f1:", f1_score(Price_test, rf_predictions, average='micro'))

MemoryError: could not allocate 665649152 bytes

In [17]:
##### KNN #####

from sklearn.neighbors import KNeighborsClassifier

clf_knn = KNeighborsClassifier(n_neighbors=3)
clf_knn.fit(X_train, Price_train)
print(clf_knn)
#knn_predictions_train = clf_knn.predict(Features_train)
knn_predictions_test = clf_knn.predict(X_test)
#print("Training CM:")
#print(confusion_matrix(Quality_train, knn_predictions_train))
#print("Training f1:", f1_score(Quality_train, knn_predictions_train, average=None))
print("Testing CM:")
print(confusion_matrix(Price_test, knn_predictions_test))
print("Testing f1:", f1_score(Price_test, knn_predictions_test, average='micro'))

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')
Testing CM:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Testing f1: 0.026449141020887405


In [ ]:
#### NAIVE BAYES #####

#from sklearn.naive_bayes import GaussianNB
#gnb = GaussianNB()
#gnb.fit(X_train, Price_train)
#print(gnb)
#gnb_predictions = gnb.predict(X_test)
#print(confusion_matrix(Price_test, gnb_predictions))
print("Testing f1:", f1_score(Price_test, gnb_predictions, average="micro"))

GaussianNB(priors=None, var_smoothing=1e-09)
